wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
weight_decay:
  desc: null
  value: 0.01
batch_size:
  desc: null
  value: 128
total_run:
  desc: null
  value: 200
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.8
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1725021531
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.10.14
      5: 0.17.8
      8:
      - 1
      - 2
      - 4
      - 5
      13: darwin-arm64
