wandb_version: 1

learning_rate:
  desc: null
  value: 0.003
weight_decay:
  desc: null
  value: 0.05
batch_size:
  desc: null
  value: 64
total_run:
  desc: null
  value: 200
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1708159984.059029
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 1
      - 2
      - 16
      - 23
      4: 3.11.5
      5: 0.16.3
      6: 4.32.1
      8:
      - 1
      - 2
      - 4
      - 5
      13: darwin-arm64
