wandb_version: 1

learning_rate:
  desc: null
  value: 0.005
weight_decay:
  desc: null
  value: 0.05
batch_size:
  desc: null
  value: 256
total_run:
  desc: null
  value: 5
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1708152779.248429
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.5
      5: 0.16.3
      8:
      - 1
      - 2
      - 4
      - 5
      13: darwin-arm64
